// Mocks generated by Mockito 5.3.0 from annotations
// in restaurant_app/test/restaurant_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:http/http.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:restaurant_app/data/api/api_service.dart' as _i4;
import 'package:restaurant_app/data/models/detail_restaurant.dart' as _i3;
import 'package:restaurant_app/data/models/restaurant.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeListRestaurant_0 extends _i1.SmartFake
    implements _i2.ListRestaurant {
  _FakeListRestaurant_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeDetailRestaurant_1 extends _i1.SmartFake
    implements _i3.DetailRestaurant {
  _FakeDetailRestaurant_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeSearchRestaurant_2 extends _i1.SmartFake
    implements _i2.SearchRestaurant {
  _FakeSearchRestaurant_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i4.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set client(_i5.Client? _client) =>
      super.noSuchMethod(Invocation.setter(#client, _client),
          returnValueForMissingStub: null);
  @override
  _i6.Future<_i2.ListRestaurant> getListRestaurant() =>
      (super.noSuchMethod(Invocation.method(#getListRestaurant, []),
              returnValue: _i6.Future<_i2.ListRestaurant>.value(
                  _FakeListRestaurant_0(
                      this, Invocation.method(#getListRestaurant, []))))
          as _i6.Future<_i2.ListRestaurant>);
  @override
  _i6.Future<_i3.DetailRestaurant> getDetailRestaurant(String? id) =>
      (super.noSuchMethod(Invocation.method(#getDetailRestaurant, [id]),
              returnValue: _i6.Future<_i3.DetailRestaurant>.value(
                  _FakeDetailRestaurant_1(
                      this, Invocation.method(#getDetailRestaurant, [id]))))
          as _i6.Future<_i3.DetailRestaurant>);
  @override
  _i6.Future<_i2.SearchRestaurant> getSearchRestaurant(String? keyword) =>
      (super.noSuchMethod(Invocation.method(#getSearchRestaurant, [keyword]),
              returnValue: _i6.Future<_i2.SearchRestaurant>.value(
                  _FakeSearchRestaurant_2(this,
                      Invocation.method(#getSearchRestaurant, [keyword]))))
          as _i6.Future<_i2.SearchRestaurant>);
}
